### PR TITLE
Documentation: Description of easier fork and branch creation and and some missing letters

### PR DESCRIPTION
**Pull request by gitolicious**
For newbies, I think the workflow by using the Github buttons is easier than manually fork and branch creation.

### CODE REVIEW

**Comment by gitolicious** [comment]
Oh wait, I just saw there is a sub-folder for each device... That should be made more clear in the documentation then...

**Comment by tekmaven** [comment]
Thanks for the two PRs today @gitolicious!! You are on 🔥!! 🥇

**Comment by gitolicious** [comment]
Thanks for the quick merges @tekmaven 
I would like to discuss the format of device templates with you and other contributors. Could you enable the "Issues" tab for the repo so I can start a conversation about it?

**Comment by tekmaven** [comment]
Sorry, I did not intend on that not being disabled @gitolicious.  Fixed!

I am working on moving the site to Gatsby.  Agree it needs *a lot* of work.  Feel free to open an issue now!

**Pull request merged**
