### PR TITLE
Create sinilink_xy_wfms.md

### PR DESCRIPTION
**Pull request by beikeland**

### CODE REVIEW

**Comment by tekmaven** [comment]
Thank you for the contribution!! This is awesome!  I want to get this device!

**Comment by beikeland** [comment]
I messed up the path, sorry!

esphome-devices/sinilink_xy_wfms/ instead of esphome-devices/_devices/sinilink_xy_wfms/

Revert and resub?

**Comment by beikeland** [comment]
@tekmaven whats the best approach to recitify messing up the paths?

**Comment by tekmaven** [comment]
@beikeland no big deal! just create a new PR to fix the issue and we will review/merge ASAP.  thanks!

**Pull request merged**
