### PR TITLE
Add Shelly EM configuration

### PR DESCRIPTION
**Pull request by kylhill**
This PR adds a new configuration to use a Shelly EM as a whole-home energy monitor for 2-phase power.

### CODE REVIEW

**Comment by pedroona** [comment]
> This PR adds a new configuration to use a Shelly EM as a whole-home energy monitor for 2-phase power.

Hi @kylhill 
I try to use you configuration in one Shelly EM and it always shoot down and overheat.
Did you install it on any Shelly EM with good results?

Thnaks in advance for your great work

**Comment by kylhill** [comment]
Yeah, I've got it running on the Shelly EM in my basement right now.   Do you have the IRQ pin set in your configuration? 
`
WARNING: Prevent overheating by setting this IRQ pin! - See https://esphome.io/components/sensor/ade7953.html
irq_pin: GPIO13
`

I'm not 100% sure if this is the right IRQ pin, as I used the pinout from https://templates.blakadder.com/shelly_EM.html.  You might try experimenting with different pins?  I'm not sure how I would confirm myself.

**Comment by kylhill** [comment]
Per https://community.openenergymonitor.org/t/shelly-em-energy-monitor/14242/12, it looks like GPIO13 is the right PIN for the IRQ.

**Comment by pedroona** [comment]
Thank you very much for your comments.
I had already read the documentation you refer to and the IRQ pin seems to be correct.
The problem that caused the device to turn off has been solved by setting a static IP.
But the NTC temperature readings are still elevated. I think it may be due to calibration.
For the calibration I have used the data from the Shelly 2PM device and it may be wrong. They are always around 120 degrees Celsius. But to the touch, the device doesn't seem to be that hot.
I hope to be able to get the correct calibration information for the sensor soon.
I am afraid to install it without knowing the correct data, since it will be inside a closet full of clothes.
What do you think? should I worry? or just setting the IRQ pin will I be safe?

thanks again in advance

**Comment by kylhill** [comment]
I wasn't aware that the Shelly EM _had_ an NTC temperature sensor.  Can you post your device configuration YAML?

**Comment by pedroona** [comment]
Of course. This is the configuration:
```yaml

substitutions:
  dev_name: shelly-em

esphome:
  name: ${dev_name}
  platform: ESP8266
  board: esp01_1m

time:
  - platform: homeassistant
    timezone: Europe/Madrid

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret general_password

# Wi-Fi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: HIGH
  fast_connect: true
  reboot_timeout: 45min
  manual_ip:
    static_ip: 192.168.0.111
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: shelly-em AP
    password: !secret general_password

captive_portal:

web_server:
  port: 80

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953
    # WARNING: Prevent overheating by setting this IRQ pin! - See https://esphome.io/components/sensor/ade7953.html
    irq_pin: GPIO13
    voltage:
      name: Shelly EM Voltage
      id: voltage
    current_a:
      name: Shelly EM Phase 1 Current
      id: current_phase_1
    current_b:
      name: Shelly EM Phase 2 Current
      id: current_phase_2
    active_power_a:
      name: Shelly EM Phase 1 Power
      id: power_phase_1
      # Consider calibrating CT clamps, measurements were closer to the stock Shelly EM firmware for me without calibration
      # See: https://community.home-assistant.io/t/anyone-using-shelly-em/149867
      #filters:
      #- lambda: if (x <= 0.0) return 0; else return x * 1.143207411;
    active_power_b:
      name: Shelly EM Phase 2 Power
      id: power_phase_2
      #filters:
      #- lambda: if (x <= 0.0) return 0; else return x * 1.143207411;
    update_interval: 5s

  - platform: template
    name: Shelly EM Total Power
    id: total_power
    state_class: measurement
    device_class: power
    lambda: return id(power_phase_1).state + id(power_phase_2).state;
    update_interval: 5s
    unit_of_measurement: W

  - platform: total_daily_energy
    name: Shelly EM Phase 1 Energy
    id: energy_phase_1
    power_id: power_phase_1
    filters:
      # Multiplication factor from W to kWh is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: Shelly EM Phase 2 Energy
    id: energy_phase_2
    power_id: power_phase_2
    filters:
      # Multiplication factor from W to kWh is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: template
    name: Shelly EM Total Energy
    id: total_energy
    state_class: total_increasing
    device_class: energy
    lambda: return id(energy_phase_1).state + id(energy_phase_2).state;
    unit_of_measurement: kWh

  - platform: template
    name: Shelly EM Total Current
    id: total_current
    state_class: measurement
    device_class: current
    lambda: return id(current_phase_1).state + id(current_phase_2).state;
    update_interval: 5s
    unit_of_measurement: A

  - platform: template
    name: Shelly EM Phase 1 Apparent Power
    id: apparent_power_phase_1
    state_class: measurement
    device_class: power
    lambda: return id(current_phase_1).state * id(voltage).state;
    update_interval: 5s
    unit_of_measurement: VA

  - platform: template
    name: Shelly EM Phase 2 Apparent Power
    id: apparent_power_phase_2
    state_class: measurement
    device_class: power
    lambda: return id(current_phase_2).state * id(voltage).state;
    update_interval: 5s
    unit_of_measurement: VA

  - platform: template
    name: Shelly EM Total Apparent Power
    id: apparent_total_power
    state_class: measurement
    device_class: power
    lambda: return id(apparent_power_phase_1).state + id(apparent_power_phase_2).state;
    update_interval: 5s
    unit_of_measurement: VA

  - platform: template
    name: Shelly EM Phase 1 Power Factor
    id: power_factor_phase_1
    state_class: measurement
    device_class: power_factor
    lambda: return id(power_phase_1).state / id(apparent_power_phase_1).state;
    accuracy_decimals: 3
    update_interval: 5s
    unit_of_measurement: "%"

  - platform: template
    name: Shelly EM Phase 2 Power Factor
    id: power_factor_phase_2
    state_class: measurement
    device_class: power_factor
    lambda: return id(power_phase_2).state / id(apparent_power_phase_2).state;
    accuracy_decimals: 3
    update_interval: 5s
    unit_of_measurement: "%"

  - platform: template
    name: Shelly EM Total Power Factor
    id: total_power_factor
    state_class: measurement
    device_class: power_factor
    lambda: return id(total_power).state / id(apparent_total_power).state;
    accuracy_decimals: 3
    update_interval: 5s
    unit_of_measurement: "%"
    
    # NTC Temperature
  - platform: ntc
    sensor: shelly_em_temp_resistance_reading
    name: "Shelly EM Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
      
  - platform: resistance
    id: shelly_em_temp_resistance_reading
    sensor: shelly_em_temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    
  - platform: adc
    id: shelly_em_temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

switch:
  - platform: gpio
    name: Shelly EM Switch
    pin: GPIO15
    id: relay
```
The idea that the Shelly EM device has an NTC sensor I have taken from its similarity with the Shelly 2PM, but surely I am wrong and that is the problem.
https://esphome.io/components/sensor/ade7953.html

**Comment by kylhill** [comment]
Yeah, from this [support post](https://m.facebook.com/groups/ShellyIoTCommunitySupport/permalink/3601666286599376)  by a Shelly engineer, it doesn't look like it has an NTC.

**Comment by pedroona** [comment]
> Yeah, from this [support post](https://m.facebook.com/groups/ShellyIoTCommunitySupport/permalink/3601666286599376) by a Shelly engineer, it doesn't look like it has an NTC.

Wow, thanks a lot for your great work and your fast response.

**Comment by ornago** [comment]
The original firmware gives an information about "returned energy", is there a chance to get the configuration extended?

**Pull request merged**
