### PR TITLE
Create gosund-p1.md

### PR DESCRIPTION
**Pull request by sanderlv**
# ATTENTION! Be aware that some of these devices can do "sudden power toggles". Meaning the relays will very shortly "toggle" and thus might harm you equipment. use this totally at you own risk.
# Although this risk is there the full functionality of these P1's can be achieved by using this ESPHome yaml. Good luck!

### CODE REVIEW

**Review by sanderlv — COMMENTED** [review]
trying to add extra return above comment to flow the git

**Review by sanderlv — COMMENTED** [review]
another try

**Comment by sanderlv** [comment]
Ok, tried my best. Don't know what or where to change.

**Comment by tekmaven** [comment]
Appreciate your contribution.  I got the linter passing and will merge it!

**Pull request merged**
